skip_non_tags: true
environment:
#    APPVEYOR_RDP_PASSWORD:
#        secure: KyDeEKZX+ICLjbuRvb6p34x45RZwzkyeEps+snuVUek=

    matrix:
      - PYTHON_PATH: C:\Python36
        VLC_INSTALL_FLAGS: '--x86'

      - PYTHON_PATH: C:\Python36-x64
        VLC_INSTALL_FLAGS: ''

#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    - "SET PATH=%PYTHON_PATH%;%PYTHON_PATH%\\Scripts;%PATH%"
    - cmd: pip install pyinstaller wxpython python-vlc
    - cmd: choco install vlc %VLC_INSTALL_FLAGS% -y --no-progress

build_script:
    - cmd: cd "%APPVEYOR_BUILD_FOLDER%\bin"
    - cmd: python build.py

after_build:
    - cmd: cd "%APPVEYOR_BUILD_FOLDER%\bin"
    - cmd: 7z a FestEngine.zip FestEngine\*

artifacts:
    - path: bin\FestEngine.zip
      name: FestEngine
