skip_non_tags: true
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      VLC_INSTALL_FLAGS: "--x86"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install pyinstaller wxpython"
  - ps: choco install vlc $env:VLC_INSTALL_FLAGS -y --no-progress
build_script:
  - cmd: cd C:\projects\festengine\bin
  - cmd: Build.bat