skip_non_tags: true
environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      VLC_INSTALL_FLAGS: "--x86"
      BUILD_FLAGS: ""
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      VLC_INSTALL_FLAGS: ""
      BUILD_FLAGS: "%PROGRAMFILES%\\VideoLAN\\VLC"
      
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: pip install pyinstaller
  - ps: pip install wxpython
  - ps: pip install python-vlc
  - ps: choco install vlc $env:VLC_INSTALL_FLAGS -y --no-progress

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\bin
  - cmd: .\Build.bat %BUILD_FLAGS%

after_build:
  - ps: 7z a bin\FestEngine.zip $env:APPVEYOR_BUILD_FOLDER\bin\FestEngine\*

artifacts:
  - path: bin\FestEngine.zip
    name: FestEngine
