skip_non_tags: true
environment:
    matrix:
      - ARCH: 'x86'
        PYTHON_PATH: C:\Python36
        VLC_INSTALL_FLAGS: '--x86'
      - ARCH: 'x64'
        PYTHON_PATH: C:\Python36-x64
        VLC_INSTALL_FLAGS: ''

install:
    - "SET PATH=%PYTHON_PATH%;%PYTHON_PATH%\\Scripts;%PATH%"
    - cmd: pip install pyinstaller python-vlc wxpython
    - cmd: choco install vlc %VLC_INSTALL_FLAGS% -y --no-progress

build_script:
    - cmd: cd "%APPVEYOR_BUILD_FOLDER%\bin"
    - cmd: python build.py

after_build:
    - cmd: cd "%APPVEYOR_BUILD_FOLDER%\bin\FestEngine"
    - cmd: del MSVCP140.dll VCRUNTIME140.dll api-ms-*  # GPL does not allow...
    - cmd: echo --- Packing a Full version ---
    - cmd: 7z a ..\full.zip *
    - cmd: echo --- Minimalizing ---
    - cmd: cd ..
    - cmd: .\minimalize.bat
    - cmd: echo --- Packing a Minimal version ---
    - cmd: 7z a ..\minimal.zip *

artifacts:
    - path: bin\full.zip
      name: FestEngine $(arch) Full
    - path: bin\minimal.zip
      name: FestEngine $(arch) Minimal
