clone_depth: 1
skip_branch_with_pr: true
image:
    - Visual Studio 2019
    - Ubuntu
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: MPAYz75AKBf954hdYvzz2VoCxy5RJLBdg0fajQ1SQUU=
  matrix:
    - ARCH: '64'
      VLC: 'latest'
    - ARCH: '32'
      VLC: '2.2.8'

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  install:
    - pwsh: |
        Import-Module -Force "$env:APPVEYOR_BUILD_FOLDER/bin/ci.psm1"
        FestEngineGetDeps

  build_script:
    - pwsh: |
        Import-Module -Force "$env:APPVEYOR_BUILD_FOLDER/bin/ci.psm1"
        FestEngineBuild

  before_test:
    - pwsh: |
        echo '--- Downloading test data ---'
        git submodule update --init 2>&1

  test_script:
    - pwsh: |
        echo '--- Running tests ---'
        & "$env:PYTHON_PATH/python.exe" -m unittest discover "./test"

  after_test:
    - pwsh: |
        Import-Module -Force "$env:APPVEYOR_BUILD_FOLDER/bin/ci.psm1"
        FestEnginePackage

  artifacts:
    - name: FestEngine $(ver) Windows $(arch)bit VLC $(vlc_version) Debug
      path: bin/festengine-$(ver)-win$(arch)-VLCv$(vlc_version)-debug.zip
    - name: FestEngine $(ver) Windows $(arch)bit VLC $(vlc_version) Full
      path: bin/festengine-$(ver)-win$(arch)-VLCv$(vlc_version)-full.zip
    - name: FestEngine $(ver) Windows $(arch)bit Minimal
      path: bin/festengine-$(ver)-win$(arch)-minimal.zip

-
  matrix:
    only:
      - APPVEYOR_REPO_TAG: true
  deploy:
      - provider: GitHub
        description: 'Auto-created Release'
        auth_token:
          secure: tpurZq/nyMadA/DqWepPmvcxhxfUL25cfvmFEDOUPUvOfNdUP4SpBH1QJm1yt06T
        draft: true
        prerelease: true
        on:
          appveyor_repo_tag: true

-
  matrix:
    only:
      - image: Ubuntu
        ARCH: '64'
        APPVEYOR_REPO_TAG: true

  install:
    - sudo apt-get update
    - sudo apt-get install -y python3-pip
    - sudo -H pip3 install -U docker-compose
  build_script:
    - ./bin/build.sh
  artifacts:
    - name: FestEngine Linux 64bit Minimal
      path: bin/fest_engine-linux-x64-minimal.tar.gz
