clone_depth: 1
skip_branch_with_pr: true
image:
    - Ubuntu
    - Visual Studio 2019
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: MPAYz75AKBf954hdYvzz2VoCxy5RJLBdg0fajQ1SQUU=
  matrix:
    - ARCH: '64'
      VLC: 'latest'
    - ARCH: '32'
      VLC: '2.2.8'


for:
-
  matrix:
    only:
      - image: Ubuntu
        ARCH: '64'

  install:
    - sudo apt-get update
    - sudo apt-get install -y python3-pip
    - sudo -H pip3 install --upgrade pip
    - sudo -H pip3 install --upgrade docker-compose
  build_script:
    - ./bin/build.sh
  artifacts:
    - name: FestEngine Linux 64bit Minimal
      path: bin/fest_engine-linux-x64-minimal.tar.gz

-
  matrix:
    only:
      - image: Visual Studio 2019

# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  install:
    - ps: |
        Import-Module -Force "$env:APPVEYOR_BUILD_FOLDER/bin/ci.psm1"
        FestEngineGetDeps

  build_script:
    - ps: FestEngineBuild

  before_test:
    - cmd: |
        echo --- Downloading test data ---
        git submodule update --init

  test_script:
    - cmd: |
        echo --- Running tests ---
        "%PYTHON_PATH%/python.exe" -m unittest discover "./test"

  after_test:
    - ps: FestEnginePackage

  artifacts:
    - name: FestEngine $(ver) Windows $(arch)bit VLC $(vlc_version) Debug
      path: bin/fest_engine-$(ver)-win$(arch)-VLCv$(vlc_version)-debug.zip
    - name: FestEngine $(ver) Windows $(arch)bit VLC $(vlc_version) Full
      path: bin/fest_engine-$(ver)-win$(arch)-VLCv$(vlc_version)-full.zip
    - name: FestEngine $(ver) Windows $(arch)bit Minimal
      path: bin/fest_engine-$(ver)-win$(arch)-minimal.zip



deploy:
    - provider: GitHub
      description: 'Auto-created Release'
      auth_token:
        secure: Ma3h2V4njIQJClEXXBbsTHnRBdtsyXKpCszdcItYhGdx8MHkKupcSZH5QMDENx1K
      draft: true
      prerelease: true
      on:
        APPVEYOR_REPO_TAG: true
