skip_non_tags: true
environment:
    matrix:
      - ARCH: '32'
        PYTHON_PATH: C:\Python36
        VLC_INSTALL_FLAGS: '--x86'
      - ARCH: '64'
        PYTHON_PATH: C:\Python36-x64
        VLC_INSTALL_FLAGS: ''

install:
    - "SET PATH=%PYTHON_PATH%;%PYTHON_PATH%\\Scripts;%PATH%"
    - cmd: pip install pyinstaller python-vlc wxpython
    - cmd: choco install vlc %VLC_INSTALL_FLAGS% -y --no-progress

build_script:
    - cmd: cd "%APPVEYOR_BUILD_FOLDER%\bin"
    - cmd: python build.py

after_build:
    - cmd: cd "%APPVEYOR_BUILD_FOLDER%\bin\FestEngine"
    - cmd: del MSVCP140.dll VCRUNTIME140.dll api-ms-*  # GPL does not allow...
    - cmd: echo --- Packing a Full version ---
    - cmd: 7z a ..\festengine-win%ARCH%-full.zip *
    - cmd: echo --- Minimalizing ---
    - cmd: cd ..
    - cmd: .\Minimalize.bat
    - cmd: echo --- Packing a Minimal version ---
    - cmd: 7z a ..\festengine-win%ARCH%-minimal.zip *

artifacts:
    - path: bin\festengine-win$(arch)-full.zip
      name: FestEngine Windows $(arch)bit Full
    - path: bin\festengine-win$(arch)-minimal.zip
      name: FestEngine Windows $(arch)bit Minimal

deploy:
    description: 'Auto-created Release'
    provider: GitHub
    auth_token:
        secure: tpurZq/nyMadA/DqWepPmvcxhxfUL25cfvmFEDOUPUvOfNdUP4SpBH1QJm1yt06T
    artifact: bin\festengine-win$(arch)-minimal.zip,bin\festengine-win$(arch)-full.zip
    draft: true
    prerelease: true
    on:
        appveyor_repo_tag: true
